#+TITLE:       Пуховая маска от BVN
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       e.lepikhin@corp.mail.ru
#+DATE:        2017-02-21
#+URI:         /blog/%y/%m/%d/пуховая-маска-от-bvn
#+KEYWORDS:    снаряжение, пух, балаклава, маска
#+TAGS:        снаряжение
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

Почтальон принёс феерический кошмар подворотен от BVN Travel (шьют для
Газпрома). Пуховая маска. Спереди пух, сзади флис. Создана для уличных
работ в полярных условиях. Весы показали 130 грамм. Цена
700\nbsp{}рублей(!).

Выглядит очень и очень неплохо, если этот речевой оборот вообще
применим к изделию. Швы качественные, крой анатомический, даже кончик
носа прикрыт планочкой. Черный цвет будет эффективно греться и сушить
на солнце. Слой расправленного пуха от 1\nbsp{}см (нос) до 3\nbsp{}см
(лоб, подбородок, щёки).

Что переделаю: весь флис сзади отрежу, вместо него пущу 2 или 3
резинки, по типу крепления фонарика. В текущем исполнении маску
непросто надеть поверх каски/шапки и в условиях ветра, а также
единственная утяжка к сожалению не прижимает маску к лицу достаточно
плотно.

Не решенная проблема: с внутренней стороны х/б 100%. Вся влага от кожи
и дыхания будет бодро уходить в пух. Пух сохнет примерно вечность. На
3-4 день от ветра маска ещё защитит, но пух явно превратится в лёд…

file:./images/bvn-down-mask1.jpg

file:./images/bvn-down-mask2.jpg

file:./images/bvn-down-mask3.jpg
