#+TITLE:       Легковесный тент из спасодеял
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       e.lepikhin@corp.mail.ru
#+DATE:        2017-10-15
#+URI:         /blog/%y/%m/%d/легковесный-тент-из-спасодеял
#+KEYWORDS:    DIY, снаряжение, легкоходы
#+TAGS:        DIY, снаряжение
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+INCLUDE: "~/.emacs.d/public/blog/setup.org"

* Идея

{{{img_center(200 грамм\, помещается в кармане куртки, ./images/MMB-tent2.jpg)}}}

Чтобы красиво опозориться на очередном [[http://mmb.progressor.ru/][ММБ]], решил на себя с [[http://leopard-fil.ru/][напарником]]
сделать лёгкий тент. Вот что получилось:

 - Размер 320×210\nbsp;см
 - Вес 196\nbsp{}гр
 - 8 оттяжек по 4 метра (многовато), каждая снабжена катушкой и
   регулятором длины

{{{img_right(Схема крепления оттяжки к тенту, ./images/MMB-tent4.jpg)}}}
Тент сделал из двухспасодеял. Скрепил их обычным скотчем. В точках
крепления оттяжек наклеил в 4 слоя армированный скотч. Затем
люверсы. В люверсы репшнур. К репшнуру оттяжка, которая из арамидной
нити (держит около 25-30\nbsp{}кг, покупал у китайцев). Почему так
сложно? Арамидная нить разрезает что угодно, в том числе саму
себя. Поэтому моей фантазии хватило на то, чтобы закрепить её к
репшнуру брамшкотовым узлом (нагрузка плавно расходится на
сравнительно обширный репшнур). Репшнур нагружает люверс, люверс
скотч, скотч равномерно передает нагрузку на спасодеяло.

* Регуляторы

{{{img_left(Общий вид регулятора, ./images/MMB-tent1.jpg)}}}
Открыл для себя новый материал\nbsp{}— оргстекло. Возмущён, что он в нашем
детстве был жутким дефицитом (да и сейчас нелегко достать, если ты не
дачник с теплицей). Из оргстекла сделал регуляторы длины, которые
одновременно и катушки для оттяжек.


4-миллиметровое оргстекло, 2×7\nbsp{}см. Загнуто под углом 90°. Две
прорези, дырочка. Получилось удобнее, чем фирменные регуляторы!
Примерно вот так это в сборе:

{{{img_center(Свободно двигается по нити\, но хорошо держит на трении, ./images/MMB-tent3.jpg)}}}
