#+TITLE:       Альпинизм\nbsp{}— не спорт!
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       e.lepikhin@corp.mail.ru
#+DATE:        2016-06-21
#+URI:         /blog/%y/%m/%d/альпинизм-—-не-спорт
#+KEYWORDS:    альпинизм, спорт, разряды, категории сложности
#+TAGS:        горы, спорт, альпинизм
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Можно ли считать альпинизм спортом?

Я знаю, что тут в ленте у меня много разрядников, мастеров и разного
рода Барсов\nbsp{}— извините.

Всю жизнь меня интересует: какому больному человеку пришло в голову
назвать альпинизм, пеший/горный/водный/вело туризм СПОРТОМ? Спорт\nbsp{}—
это состязание, где в максимально равных условиях соревнуются тела и
умы. Например, мировой рекорд на 100-метровке не засчитывается, если
скорость ветра более 2 метров в секунду(!). Но какое присвоение
разрядов (СПОРТ!) может быть в горовосхождении? Вчера на гору зашли
даже зелёные чайники в газосварочных очках, а сегодня из-за сложнейших
условий там погибли мастера спорта с лучшим снаряжением. Каким боком
тут равные условия? Вчера реку туристы шли по низкой воде, а сегодня
там несёт стволы деревьев. Вчера всё было хорошо, а сегодня на
перевале словили камнепад, который перебил веревки. Давайте уже
перестанем кричать громче всех на этой ярмарке тщеславия и признаемся
сами перед собой: мы играем в игру, где известно от силы 1/10 всей
информации (простите за отсылку к теории игр). Т.е. как бы мы ни
старались, а в равные условия игроков поставить не нельзя, а
следовательно СПОРТОМ это быть не может по определению. В этих видах
деятельности соревноваться можно с самим собой, но уж точно не с
окружающими.

Дальше ещё круче. Альпинизм как вид спорта известен только на
территории бывшего СССР. Нигде больше в мире такого "спорта"
нет. Сейчас на высшие достижения работают от силы 50 человек (тут
просто достаточно осознать, что на чемпионат России заявляются по
20-30 человек, когда как формально допуск имеют как минимум
сотни). Продолжая сравнения с бегом представьте, что марафон из 2:40
за год в России выбегают только 20-30 человек, а стремятся к этому
лишь 50 человек. Смешно, но грустно.  Это практически театр одного
актера: сам с собой посоревновался, сам себя победил, сам себя
наградил и поздравил. Т.е. репрезентативность подиума для выявления
действительных биологических чемпионов равна практически нулю.  Ещё
смешнее, когда на сцену выходит чемпионат МИРА, в котором участвуют 10
стран, включая простите Монголию. Это тотальная победа пафоса над
здравым смыслом.

Всё это так и оставалось бы смешным историческим недоразумением, если
бы в Мин.спорта действительно не были зарегистрированы вот эти все
чемпионаты, звания и т.д. Вот в этом году был запущен "проект высота"
(поищите в интернете). Мотивация его запуска\nbsp{}— в мин.спорта утверждена
сборная страны по высотному альпинизму, а сборной нет. СБОРНАЯ СТРАНЫ
В ДЕЯТЕЛЬНОСТИ, ГДЕ НА ВСЮ СТРАНУ СПОРТСМЕНОВ 50 ЧЕЛОВЕК, ГДЕ В
ПРИНЦИПЕ НЕ ПОЛУЧИТСЯ СОРЕВНОВАТЬСЯ, И КОГДА ВЕСЬ ОСТАЛЬНОЙ МИР ДАЖЕ
НЕ В КУРСЕ, ЧТО ЭТО СПОРТ. И вот значит собрали толпу 50 человек,
тратит государство на каждого из них по примерно $4000 в год (моя
оценка), чтобы они стали чемпионами мира в спорте, которого не
существует...  Масштабы распила конечно далеко не сердюковские, но
степень маразма по-моему гораздо выше, чем у московских жёлто-зеленых
бордюров.

Это же касается и пешего/горного/водного туризма, но для него это
недоразумение уже практически в прошлом.

Извините, накипело. Простите, разрядники-мастера, вы все хорошие
ребята, просто мне очень сильно кажется, что не надо петь песни на
этой ярмарке.
