#+TITLE:       Самодельные снежные якоря
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       e.lepikhin@corp.mail.ru
#+DATE:        2016-05-15
#+URI:         /blog/%y/%m/%d/самодельные-снежные-якоря
#+KEYWORDS:    DIY, снаряжение
#+TAGS:        DIY, снаряжение
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Самодельные снежные якоря для палатки из пластика бутылок

Это третья версия снежных якорей для палатки. Мой велосипед. Мотивация
их создания: палатка, установленная на кошки, ледорубы, палки, кружки
ложки и тапки внезапно создает ряд проблем т.к. утром понадобятся кошки,
ледорубы, палки, кружки и ложки, а палатка должна стоять.

Средний вес 19 грамм, изготовил 12 штук.

В прошлом году были якоря такой же площади[fn::Вторая версия не
удалась также потому что репшнур резал одинарный пластик. Была также
грубо сделанная экспериментальная первая версия, похожая на купольный
парашют, не слишком надежная и тяжелая]. После перемерзания снега их
приходилось из сугроба вырубать ледорубом. На первоначальное смерзание
нужны буквально секунды, просто притоптать. Ну, тут как с закопанной
кружкой.

В этой версии сделана система, теоретически позволяющая вытаскивать
якоря без существенной работы лопатой/ледорубом[fn::идея от Евгения
Шваба].

#+CAPTION: Общий вид. Размер примерно 25x10\nbspсм.
file:images/snow-anchors1.jpg

Чтобы проще было выдергивать из смерзшегося снега, сделал
ромбообразную форму, а оттяжку сделал с возможностью разъединения кольца:

#+CAPTION: С одной стороны крючок. К нему же крепится оттяжка палатки.
file:images/snow-anchors2.jpg

#+CAPTION: Со второй стороны кольцо.
file:images/snow-anchors3.jpg

Пришлось подумать как надежно сделать соединение якоря с оттяжкой. В
результате, согнул его в 4 слоя и пробил люверсами. Пластик не режет
даже если на якоре повиснуть.

#+CAPTION: Способ крепления оттяжки.
file:images/snow-anchors4.jpg

Впервые ходил с такой конструкцией в 2013 году на п.Ленина,
п.Корженевской и п.Коммунизма. Даже та первая версия здорово
помогла. С этой версией ходил на Ленина в 2016 году и ездил в Безенги
и на Эльбрус в 2016-2017\nbspгг.
