#+TITLE:       Как нельзя ремонтировать палатку
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       e.lepikhin@corp.mail.ru
#+DATE:        2017-10-07 Sat
#+URI:         /blog/%y/%m/%d/как-клеить-палатку
#+KEYWORDS:    снаряжение
#+TAGS:        снаряжение
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

* «Я все починил!»

Дал платку в небольшой недельный поход. Вернули с радостью на лице и
словами «мы тебе её немного починили». Я не придал значения, а вот
недавно распаковал и увидел. Была маленькая дырочка, заклеенная
армированным скотчем (каюсь, забыл починить после Эльбруса). Скотч
отодрали, поверх стежком около 0.3 мм пришили кондовую заплатку. Что в
итоге? Была дыра 3 см, стала дыра 30 см по периметру.  Палатка
пережила летний и зимний Эльбрус, базовый лагерь под Ленина, Кодар,
черт знает сколько всесезонных выездов в Саяны, на Хамар-Дабан, на
Кавказ и в Подмосковье. Но чуть не умерла от ремонта.

Полдня убил чтобы аккуратно снять швы (зря старался, как видите ткань
уже поползла). Теперь буду клеить.

Запомните два правила:
1. Палатки НИКОГДА не шьют. Исключение - порвалась по шву. Но и там
   особая техника. Заплатки исключительно приклеивают, предварительно
   обезжирив.
2. Чужое снаряжение без полного согласования не ремонтируют. «Может
   этот шнурок кому-то очень был нужен?»

#+CAPTION: Вот такую красоту я увидел, когда распаковал палатку.
file:./images/tent-wrong-repair1.jpg

#+CAPTION: Вид с изнаночной стороны.
file:./images/tent-wrong-repair2.jpg

#+CAPTION: Вот так выглядит палатка под пришитой заплаткой.
file:./images/tent-wrong-repair3.jpg

[[file:tent-correct-repair.org][Продолжение истории: как чинить правильно]].
