#+TITLE:       Как правильно ремонтировать ткани наряжения
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       e.lepikhin@corp.mail.ru
#+DATE:        2017-05-07
#+URI:         /blog/%y/%m/%d/как-правильно-ремонтировать-ткани-наряжения
#+KEYWORDS:    DIY, снаряжение, ремонт
#+TAGS:        DIY, снаряжение, ремонт
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+INCLUDE: "~/.emacs.d/public/blog/setup.org"

[[file:./как-клеить-палатку][С чего всё началось]]

Раз уж на то пошло, пост о том как я клею палатки, спальники, пуховки
и что угодно ещё, сделанное из тонкой современной ткани.

Если клеим палатку, то лучше заплатку ставить на наружную сторону,
поскольку внутри ткань покрыта силиконом или полиуретаном. Там
заплатка рискует отвалиться вместе с пленкой
покрытия. Исключение~--- мембранные ткани, их все равно с какой
стороны клеить т.к. мембрана между слоями ткани.

Заплатки держатся достаточно надёжно, несколько лет. Как я писал, в
том числе без фатальных разрушений переносят химчистку и стирку.

Заплатку закругляю, так будет меньше цепляться. Обезжирил ацетоном обе
поверхности, нанёс слой клея Кристалл, дал подсохнуть 5 минут.

{{{img_center(Нанести клей на палатку., ./images/tent-correct-repair1.jpg)}}}

{{{img_center(Нанести клей на заплатку., ./images/tent-correct-repair2.jpg)}}}

Выждал несколько минут, чтобы клей подсхох, после чего прижал заплатку
на ровной поверхности. Как и при наклейке обоев, движениями от центра
разгладил, прижал и выдавил пузыри воздуха.

{{{img_center(Я использовал игрушечную скалку\, чтобы хорошо раскатать., ./images/tent-correct-repair3.jpg)}}}

{{{img_center(Через полчаса капнул клей в места\, где плохо проклеилось., ./images/tent-correct-repair4.jpg)}}}

{{{img_center(Чтобы край лучше держался\, провел ободок из клея., ./images/tent-correct-repair5.jpg)}}}

