#+TITLE:       Как правильно ремонтировать ткани наряжения
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       e.lepikhin@corp.mail.ru
#+DATE:        2017-05-07
#+URI:         /blog/%y/%m/%d/как-правильно-ремонтировать-ткани-наряжения
#+KEYWORDS:    DIY, снаряжение, ремонт
#+TAGS:        DIY, снаряжение, ремонт
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

[[file:./как-клеить-палатку][С чего всё началось]]

Раз уж на то пошло, пост о том как я клею палатки, спальники, пуховки
и что угодно ещё, сделанное из тонкой современной ткани.

Если клеим палатку, то лучше заплатку ставить на наружную сторону,
поскольку внутри ткань покрыта силиконом или полиуретаном. Там
заплатка рискует отвалиться вместе с пленкой
покрытия. Исключение\nbsp{}— мембранные ткани, их все равно с какой
стороны клеить т.к. мембрана между слоями ткани.

Заплатки держатся достаточно надёжно, по несколько лет (пока
отвалилась по-моему только одна из штук 20). Как я писал, в том числе
без фатальных разрушений переносят химчистку и стирку.

Заплатку закругляю, так будет меньше цепляться. Обезжирил ацетоном обе
поверхности, нанёс слой клея Кристалл, дал подсохнуть 5 минут.

#+CAPTION: Нанести клей на палатки.
file:./images/tent-correct-repair1.jpg

#+CAPTION: Нанести клей на заплатку.
file:./images/tent-correct-repair2.jpg

Выждал несколько минут, чтобы клей подсхох, после чего прижал заплатку
на ровной поверхности. Как и при наклейке обоев, движениями от центра
разгладил, прижал и выдавил пузыри воздуха.

#+CAPTION: Я использовал игрушечную скалку, чтобы хорошо раскатать.
file:./images/tent-correct-repair3.jpg

#+CAPTION: Через полчаса капнул клей в места, где плохо проклеилось.
file:./images/tent-correct-repair4.jpg

#+CAPTION: Чтобы край лучше держался, провел ободок из клея.
file:./images/tent-correct-repair5.jpg
