#+TITLE:       Зачем мы ходим в горы?
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       e.lepikhin@corp.mail.ru
#+DATE:        2017-10-06 Fri
#+URI:         /blog/%y/%m/%d/зачем-мы-ходим-в-горы
#+KEYWORDS:    горы, психология, философия
#+TAGS:        горы, психология, философия, жизнь
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Ответ на вопрос зачем мы ходим в горы и всё такое

Зачем дети хотят стать космонавтами? Зачем наркоманы ушатывают себя
наркотиками? Зачем люди читают художественную литературу? Зачем люди
увлекаются психологическими практиками? Для сознания всё это врата в
другие миры. Уход от обыденности. The journey. Кому-то достаточно для
этого поехать в ближайший подмосковный лес посреди лета. Кто-то этих
лесов насмотрелся за 50 лет жизни и под старость лет их тянет на
высоту или в Антарктиду. Или наоборот на Манхэттен. Одним в качестве
стимулятора прокатывает кружечка чая с хорошей книжкой, другим надо
ушатать себя до изнеможения (чего уж там, одна из самых древних
практик у шаманов…).

Я сам хожу на высоту ради переживаний пребывания в другой
вселенной. Это другой быт, воздух, солнце, почти чёрное дневное небо,
другие мысли и отношения. Во время двухмесячной экспедиции
воспоминания об обычной жизни кажутся сном недельной давности. Далёким,
забытым и бредовым. Если кратко, то люди ходят в горы ради этого. А не
ради красивых закатов и званий.
