#+TITLE:       Как я провёл лето, осень и вообще всё детство
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       johnlepikhin@gmail.com
#+DATE:        2017-12-02 Sat
#+URI:         /blog/%y/%m/%d/как-я-провёл-лето-осень-и-вообще-всё-детство
#+KEYWORDS:    юмор
#+TAGS:        юмор
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>


В назидание будущим взрослым, чтобы они не думали, что наблюдаемое ими
будущее поколение детей живёт скучно, а они сами в их возрасте были
о-го-го!..

Сказка-эпос для современных детей, чтобы они не думали, что их жизнь\nbsp{}—
единственная возможная.

Брошюра-справочник для тех кто старше меня. Ведь наверняка они знают
не все истории!

Или сказ о том, как я стал Мастером Замедленного Времени.

Однажды ко мне в гости зашел девятилетний сосед Ренат. Наши родители
всё световое время пропадали на работах, а мы это же время
пропадали... да где мы только не пропадали и куда мы только не
попадали! Так вот, в гости пришел Ренат. Чем-то надо было развлекать
гостя. Строить с будущим медиком изощрённые перфокарточные лабиринты
для хомячков уже надоело. Картошку в кладовке в тайне от родителей мы
выращивать уже пробовали. Аккордеон недавно доломали. Спички как-то
уже не привлекали внимание. Но у меня было кое что интересное,
оставшееся после недавнего ремонта дома. Растворитель! Если его
поджечь, то он горит долго, ярко и вообще не шел ни в какое сравнение
с тем, что мы пробовали поджигать до этого. Но я осознавал, что
растворитель хоть и не называется бензином, но явно имеет родственную
душу. Поэтому на уровне интуиции отделял небольшое количество эликсира
вечного счастья от бутылки и только потом брал в руки спички. Все
опыты мы проводили на кухонном противне. Это было правило
пожаробезопасности, да и вообще лить растворитель прямо на пол мне
казалось глупой идеей.
Раз налили лужицу, подожгли. Догорела. Два налили лужицу, подожгли,
почти догорела, зажгли от неё следующую спичку. Три налили
лужицу. Догорает. Тут Ренат берёт в руки пластиковую бутылку с
растворителем, и дальше я как в замедленном кино смотрю, как он
наклоняет ёмкость над догорающей лужицей, тонкая струйка льётся вниз,
а навстречу, вверх по ней поднимается пламя. Всё это случилось за долю
секунды, но для меня время растянулось в полнометражный фильм.

* Дао замедлителя времени

Следующие серии этого фильма были не столь захватывающими. Ренат
стоял, держа в руках полыхающую бутылку, края которой быстро
оплавлялись, и неустанно на неё дул с выпученными глазами. Потом он
начал ей трясти. Горящие капли растворителя летели на меня и во все
стороны. Потом бутылка упала и новый красивый пол из ДВП стал ещё более
красивым и, я бы сказал, почти живым. Ренат кинулся к окну, отодвинул
в сторону шторы (они тут же заполыхали) и закричал в форточку
"пожар!!", а потом мы вместе весело побежали за тазиком с водой. Вылили
таз воды на пол, горящий растворитель начал плавать на поверхности
воды и гореть. Вода моментально закипела, пол из ДВП окончательно ожил
и начал пучиться. Чтобы пол от нас не убежал мы накрыли его тазиком, а
сверху всё накрыли каким-то одеялом. Это и потушило уже догорающие
остатки растворителя.

До прихода родителей оставалось ещё часов 5, поэтому мы, полные
оптимизма, принялись за уборку. Я наждачкой прошелся по ножкам
стульев, от чего они почти перестали быть чёрными. Ренат тряпочкой
оттирал стол и часть стены. Обгоревшую до середины штору мы решили
оставить как есть, поскольку быстрого инженерного решения проблемы
никто из нас придумать не смог. Драили кафель, успокоили оживший пол и
почти что вернули ему исходную форму. Во всяком случае, пузыри на нём
торчали уже не на 5 сантиметров, а всего на три. На мой взгляд,
количество наших стараний в этот вечер было так велико, что
заслуживало высших похвал. Тем не менее в 8 вечера, Ренат с видом
Винни Пуха, покидающего гостеприимного Кролика, ретировался домой. А я
на всякий случай пошел на вечернюю прогулку, где решил на всякий
случай задержаться до темноты.
Потом меня вернули домой и понял, что, кажется, уборка нам удалась не
совсем. В квартире вонь, чёрный потолок на кухне, чёрный стол, чёрные
стулья, огрызок шторы и живой, гуляющий под ногами пол.

* Бычок

В детском саду были мы. Детский сад был со всех сторон в заборе. А ещё
в заборе была дырка, через которую мы в этот детский сад и попали.

Мы залезли на крышу веранды и дежурно светились там в лучах солнца,
детства и вневременья. Край крыши прогнил и там совершенно не
эстетично торчала доска. Гнилая, с гвоздём. Из лучших побуждений, я
решил это исправить. Подошел к краю и стал ногой эту доску
долбить. Ну, она и кончилась.

Прилетел я с трёхметровой высоты на плотную землю, утоптанную табунами
поколений детей землю ровно на шею. Внутри что-то свело так, что я
буквально не мог дышать минуту, рёбра и диафрагму просто свело
судорогой. Пока не отпустило делать было нечего, поэтому я смотрел
короткометражный фильм, в котором я летел вниз и думал: "жаль что я не
птица... и даже не кошка...".

* Поваренная книга пиротехника

Мне восемь лет. Тот же детский сад. Друг где-то раздобыл строительные
патроны. Мы по-быстрому развели в детском саду костёр и закинули туда
эти патроны, прикрыв их каким-то куском шифера, чтобы посмотреть, как
пули пробьют шифер. Так мы узнали, что шифер взрывается гораздо
веселее строительных патронов.
Позже мы эти патроны взрывали в водосточных канавах, в старых
унитазах и даже в руках. Но в душе навсегда осталась выбита не имеющая
смысла татуировка: "Не забуду шифер родную".

Мне девять лет. Какой-то недалёкий продавец в хозяйственном магазине
продал мне настоящую дымовую шашку. Скорее всего, она была
предназначена для садовых целей, но поскольку сделана была из металла
и имела военный тёмно-зеленый цвет\nbsp{}— сомнений не оставалось. По
случаю такого праздника собрал друзей и мы пошли на испытания в
лес\nbsp{}— от греха подальше. Но что-то пошло не так и нашего терпения
хватило только до входа в НИИ Земной Коры иркутского Академгородка. У
входа росли красивые ели редкой голубой породы. В них-то мы и запалили
шашку. Дым пошел. Нет не так. Пошло бешеное, неистовое количество
дыма, не сравнимое по красоте эффекта ни с какими дымовушками из
расчёсок или шариков для настольного тенниса! Я попытался заткнуть
дырку пальцем. Скоро пальцу стало горячо, но дым из жерла этого
маленького карманного ада так и не перестал валить. Мы спешно начали
закапывать её в землю, но поняли, что условия видимости сработали
против нас и мы замечены вместе со всем дымом, елями редкой породы и
входом в Институт Земной Коры. И мы побежали бросив всё, точнее\nbsp{}—
столь ценную покупку. Остановились мы только метров
через 200. Обернувшись мы увидели, как последние окна Института Земной
Коры плавно исчезают в клубах белоснежного дыма.  Говорят, больше
насекомых на тех ёлках никто не видел.

Мне десять лет. У друга папа в прошлом охотник. В нашем распоряжении
целая банка пороха и пара охотничьих патронов. Сыпали порох дорожкой,
делали бомбочки. То ли порох сырой, то ли руки у нас не оттуда, но
шифер круче.

Мне одиннадцать лет. По комнате летает комар. Очень он меня
утомил. Взял аэрозольный баллончик, примотал изолентой свечку. Свечку
зажег. При нажатии на клапан баллончика получалось пламя 40
сантиметров. Огнемет! Комара впечатлить не удалось, зато впечатлился я
сам. Копчёный потолок, вторая версия.
Зато аналогичный огнемет мы затем использовали для уничтожения осиного
гнезда, которое появилось между стыками панельного дома прямо под
окном моего друга. Уничтожение было удачным, правда нас тоже хорошо
покусали.

Мне двенадцать лет. С моим другом Женей Зоркальцевым отдыхаем у него в
гостях на балконе. Скучно. Женя приносит бутылку растворителя, на этот
раз стеклянную. Наливаем лужицу, поджигаем, зачарованно смотрим как
она сгорает, наливаем следующую.
И тут Женя решает, что не экономно так тратить время и решает полить
ещё не потухшую лужицу из бутылки... В этой серии замедленного кино
божественный актёр абсолютно молча, с серьезным сосредоточенным лицом
и важным видом обмахивал меня своим огненным кадилом. Сюжета не
сложилось: загорелись какие-то тряпки в углу балкона, которые мы
успешно выкинули за борт (впрочем, если бы удалось поджечь
соседей\nbsp{}— получилось бы интересней.
Позже Женя украсил искусственную ёлку настоящими свечами. Так он стал
первооткрывателем здоровенной дырки посредине ковра.

Мне тринадцать лет. Я уже освоил азы физики элементарных частиц и без
проблем делал бомбы с удалённым взрывателем из подручных горючих
веществ, аккуратно разбитой трехвольтовой лампочки и батарейки. Мой
друг и одноклассник Серега Грозов строит нешуточные планы взорвать
нашу любимую школу. Дело принимает неожиданный поворот, когда он на
полном серьезе предлагает мне применить мои инженерные наработки для
осуществления этого коварного плана. К сожалению, дальше нескольких
тестовых взрывов в трещинах школьного парапета дело как-то не пошло.

Мне восемнадцать лет. Я уже старый опытный пиротехник. У меня в
квартире есть собственный угол для безумных экспериментов и
самодельный, частично обитый железом стол. Расположен он в
полукладовке, где темно (бывшая часть подъезда). Поэтому я сижу при
свечах. Романтика! Так вот, три больших петарды уже разобраны, а я
уверенными движениями пассатижей разбираю четвертую, и вытряхиваю
содержимое на стол. Там уже скопилась немаленькая куча неизвестного
взрывоопасного вещества. И тут я в этой куче что-то замечаю. Но темно,
не видно. Наклоняюсь поближе... пододвигаю свечку. Дальше происходит
какая-то вспышка неясного происхождения, в результате которой моё лицо
становился чёрным и частично лысым, а стол пустым. В чём причина я до
сих пор не знаю, возможно в воздухе была горючая пыль.

Мне девятнадцать лет. Кульминацией опытов стал успех: я стал
файер-мэном. Сначала я плевался огнём (точнее, керосином) в лесу, на
всякий случай поближе к большому сугробу. Потом мы выплевывали
двухметровые струи огня на бард-фестивале. И наконец, мы это сделали в
самом центре Иркутска, со сцены острова Юность, где мы первый и
последний раз были организаторами метал-фестиваля.

* Кружок юного техника

Вкус к высоким энергиям я ощутил в довольно раннем возрасте. Ощутил
его буквально\nbsp{}— попробовал 220 вольт на язык. Был у нас кассетный
магнитофон. Ещё из тех, которым можно было зажать одновременно play и
fast forward и получить смешную быструю музыку. Но в один прекрасный
день он почему-то перестал включаться. Начал разбирать(ся). Вроде всё
нормально. Тогда, как истинный будущий сисадмин, решил начать с
проверки питания. Но как это сделать, если такой штекер ни в какой
другой прибор не воткнуть, а вольтметр куда-то делся? Правильно, на
язык! В глазах потемнело сразу и, почему-то, совершенно неожиданно. А
магнитофон потом как-то сам починился.

Это был бесценный опыт, в результате которого я узнал, что
электричество\nbsp{}—страшная сила. Но у нас в квартире была и другая, не
менее страшная сила: тараканы. Тут ведь надо как это?
тех.. технически! Взял картонку, наклеил почти вплотную друг к другу
два кольца фольги и в центр положил моего самого любимого варенья. К
фольге присоединил провода, засунул их в розетку.
Первые полчаса ни один таракан не пришел. За следующие 5 часов к
сожалению тоже. Поэтому пришлось взять себя в руки и пойти искать
тараканов, чтобы позвать их так сказать за праздничный стол. Тараканы
шевелили усами и говорили:

\nbsp{}— Спасибо за приглашение, но сейчас мы не при туалете и вообще
предпочитаем есть после заката.

На что я тоже шевелил воображаемыми усами и как бы отвечал им

\nbsp{}— Ах, к чему эти условности! Когда же ещё представится шанс братьев
по дому угостить любимым вареньем?

Но усы тараканов снова торчали из-под плинтуса, жестикулируя:

\nbsp{}— Вы столь любезны и ваше варенье так привлекательно пахнет, но
мы ведем скромную жизнь и предпочитаем крошки с вашего стола.

Тут лимит моего коварного благородства был исчерпан и я привычным
жестом поймал самого неосторожного за усы и вытянул из-под плинтуса.

Таракан почему-то наотрез отказывался идти к варенью через фольгу под
высоким напряжением. Поэтому я посадил его в центр круга, к
варенью. Варенье его не привлекло, но зато он сразу побежал по фольге
к гибельной для него, но заветной для меня прорези в фольге. На ней он
как-то неестественно подпрыгнул и побежал дальше, показав на прощание
язык, или что там у них вместо него.

Позже, похожие две пластины с проводами я использовал сначала в
попытках получить по отдельности кислород и водород, а потом и для
получения хлора и прикольной воды зеленого цвета.

К сожалению, чистый хлор мне получить тоже не удавалось, поэтому с
соляной кислотой была некоторая напряжёнка, что блокировало выполнение
десятков химических опытов. Но потом она каким-то непостижимым образом
у меня всё-таки появилась, причем в концентрации чуть ли не 80%. Дело
сразу пошло веселее: проплавил несколько сквозных дырок в ковре
(точнее, они появились сами собой, но я уверен что здесь как-то
замешан тот бутылёк с кислотой), получил пару химических ожогов.

Позже подруга родителей необдуманно подарила мне "химический
конструктор", но к сожалению самым любопытным веществом там оказался
магния перманганат, который в некоторых соединениях был способен
накалить пробирку до сногсшибательных температур, а также классно, аж
до временной слепоты сгорал со стружками магния, который мы невесть
где добывали.

Так вот, электричество. Где-то начиная с возраста 8 лет у меня в доме
непостижимым образом начали скапливаться радиодетали. Подозреваю,
какой-то недоброжелатель даже специально подкидывал их мне в ящик
стола, где и без них уже творилось невесть что. Одним из первых
экспериментов был уличный громкоговоритель. Соединил откуда-то
взявшийся микрофон с материализовавшимся из воздуха динамиком, добавил
батарейку. Выставил громкоговоритель в форточку, а сам с микрофоном
спрятался. Шалость удалась! За несколько дней эксперимента мы успели
спросить у прохожих всё, начиная от времени и заканчивая научными
вопросами сомнительной ценности. Большинство игнорировали, но
некоторые мило отвечали.

Я паял цветомузыку. Я паял приёмники (а кто не паял?). Я паял
усилители. Я паял передатчики с многокаскадными усилителями. Половина
из этого не работала, вторая половина неожиданно даже что-то
производила. Когда не хватало деталей, мама пустила меня на задний
двор Иркутского Вычислительного Центра, где она работала научным
сотрудником. Там как раз заканчивали разбирать такие же разрушители
устаревший суперкомпьютер. Я не знаю что разрушили они кроме
суперкомпьютера, но я дома улучшил довольно много техники. Например,
однажды мне понадобился конденсатор на 20 микрофарад. Я знал, что
именно такой стоит у папы в радиоприемнике. Разобрал, аккуратно
выпаял. Включил радиоприемник. Работает. Ну, значит лишний. Забрал
себе, приемник собрал обратно. А потом оказалось что не лишний
т.к. без него приемник не ловил половину волн. Починил его
сосед-радиотехник дядя Юра, быстро заметив пропажу.

Баночные конденсаторы вообще были большой ценностью среди
молодежи. Ведь как известно они круто дымили, если засунуть их в
розетку. Но меня после истории с дымовой шашкой это мало
привлекало. Тем не менее, иногда для душевного этдыха этим баловался и
я. А потом засунул в розетку искуссно загнутый гвоздь и в доме выбило
пробки, гвоздь из розетки почему-то вылетел со свистом, а я увидел ту
самую искру, из-за которой у меня потемнело в глазах, когда я
попробовал розетку на вкус.

* Шляпа волшебника

Балкон Жени Зоркальцева был ровно над аркой, по которой оживленно
ходили люди. И у Жени была странная привычка: плевать с балкона. Не
было никакой цели попасть в людей, но однажды он попал. Ровно в шляпу
директора нашей школы. Он нас не увидел и скорее всего даже не заметил
плевка, но какая-то шестеренка в мироустройстве всё же поломалась. В
не столь отдалённом будущем Женя решил кому-то позвонить, взял
телефонную трубку, набрал номер, но вместо привычных гудков услышал
разговор этого самого директора (его голос мы знали очень хорошо) с
неизвестным лицом. Они обсуждали коррупционную схему поставки газовых
баллонов мимо кассы.

Вообще, проводные телефоны\nbsp{}— великое изобретение вселенского
эфира. Мы не было лет 14. Я провёл себе в комнату телефонную линию и
присоединил к ней подаренную отцом Жени телефонную трубку. Телефон
получился фиговый и тихий, зато он уверенно ловил радио "Волна
Байкала"! Вечерами перед сном я часами слушал радио. По телефону.

* Я, турист

1999 год. Я уже известный фидошник, поэтому имею кучу не совсем ясно
откуда взявшихся друзей и даже собственную FTN-сеть, где я царь и
бог. Раз в несколько недель у нас оффлайн-встречи. На них мы заняты
высоко философскими беседами о роутинге, пассинге и тоссинге и
патчинге. Встречи иногда затягивались допоздна, поэтому группе
наиболее глубоко заинтересованных в вопрос приходилось нетвердым шагом
идти ко мне, брать одноместную брезентовую палатку-двускатку, уходить
в ближайший лес и там впятером в этой несчастной палатке
ночевать. Те кто не поместился в одноместную палатку - спали у костра
под куском полиэтилена.

2001 год. Друг купил палатку с печкой "Зима" и мы все вместе поехали
на берег Байкала её испытвать. Был день дураков, чем я не преминул
воспользоваться. Пилили дрова двуручной пилой. Что-то пошло не так и я
прошелся себе по основанию пальца. Во мне сразу же проснулся юный
анатом, поскольку захватывающе интересно было наблюдать, как двигаются
сухожилия. Девушки вокруг в шоке, но я уже тогда начал строить из себя
прожжённого туриста, поэтому одной рукой махнул, а второй оторвал клок
мха и приложил к ране. Балбес. Тем не менее, помогло. Даже не
загнила. С тех пор у меня красивый шрам на правой руке.

Симметричный шрам на указательном пальце левой руки я заработал после
метал-фестиваля, на выходе с которого нас ждала угрюмая, жуткая толпа
гопников с битами. Я взял бутылку, разбил её о бордюр, мощно
порезался, залил кровью тротуар, после чего меня, контуженного,
отправили домой на заслуженный отдых. К сожалению, я так и не
узнал чем закончилась одна из самых эпичных встреч сил зла и зла.

Однако эти два эпизода открыли во мне новые таланты. Теперь
эксперименты часто оканчивались гипсом, зашитыми дырками в теле,
сотрясениями мозга и операциями. Я научился сам себе колоть
обезболивающие в любую часть тела, гипсовать, на 100% точно определять
переломы, выучил латинские названия сотни костей, мышц и сухожилий,
что безусловно помогло в дальнейшем.

В общем, жизнь у нас была веселая, не то что у нынешнего
поколения. Или это всё сказки?
