#+TITLE:       Можно ли наблюдать запутанные кванты в поликлинике?
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       e.lepikhin@corp.mail.ru
#+DATE:        2017-08-03
#+URI:         /blog/%y/%m/%d/можно-ли-наблюдать-запутанные-кванты-в-поликлинике
#+KEYWORDS:    юмор, жизнь
#+TAGS:        юмор, жизнь
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

Можно ли наблюдать запутанные кванты в поликлинике или рассказ для
тех, кто всё ещё ничего не понял :)

Стоим в очереди в Пятёрочке. Перед нами на ленте чьи-то продукты. Кто
их хозяин~--- никто в округе не знает; он либо где-то среди нас в
очереди, либо где-то в торговом зале спокойно выбирает продукты. С
вероятностью 50/50 он либо у кассы, либо в зале. Пока Наблюдатель его
не пронаблюдал, его положение одновременно и здесь, и там. Иначе
говоря, хозяин этих продуктов в суперпозиции.

Вот лента с продуктами движется и продукты покупателя, находящегося в
суперпозиции, подъезжают к кассиру, который и есть
Наблюдатель. Наблюдатель громко кричит: «чьи продукты?!» Никто не
откликается. Ага, покупателя у кассы нет, он примерно в зале. Всё,
больше он не в суперпозиции, теперь его положение известно с точностью
до скорости (энергии) его перемещений по залу.

Другая ситуация: очередь в поликлинике. Вот пришла бабушка, которая
говорит: «я Алла Петрова, я там заняла у терапевта, а тут я буду за
вами». И тут же исчезает в неизвестном направлении. Следом за бабушкой
пришла многодетная мать и заняла очередь за бабушкой. Так происходит
много раз с разными людьми. Потом приходит та самая бабушка, и на
всякий случай занимает очередь ещё раз, поскольку мы-то тоже ушли
(чтобы успеть занять очередь в любимый рентген-кабинет), а кто были
все люди за нами ей неведомо. И снова исчезает.  В какой-то момент всё
запутывается настолько, что никто уже понятия не имеет кто, куда и
зачем стоит, у кого что болит и есть ли вообще в этом смысл. Абсолютно
все участники всех очередей находятся в суперпозициях: они в куче
очередей одновременно, но никто не знает, в какой очереди находится
тот или иной участник событий. Но прекрасно здесь то, что это не
просто хаос, здесь каждый участник запутан на других, хоть и находится
в суперпозиции. И в тот момент, когда открывается дверь Наблюдателя и
медсестра кричит: «Алла Петрова!»~--- разрушается суперпозиция ВСЕХ
запутанных людей в очереди, потому что тут же из ниоткуда появляется
Алла Петрова, переругиваясь объясняет многодетной матери что она здесь
первая заняла, и что за многодетной матерью на самом деле какой-то дед
(её муж), который сейчас у проктолога, а вовсе не парень в наушниках,
который вообще не знает куда попал и что здесь делает. Всё, кванты
больше не запутаны.

yt:JD_lHt4JmOI
