#+TITLE:       Что такое свобода~--- почти по Пелевину
#+AUTHOR:      Evgenii Lepikhin
#+EMAIL:       e.lepikhin@corp.mail.ru
#+DATE:        2017-10-01
#+URI:         /blog/%y/%m/%d/что-такое-свобода-—-почти-по-пелевину
#+KEYWORDS:    жизнь, психоделика, сны
#+TAGS:        жизнь, психоделика, сны
#+LANGUAGE:    ru
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

На днях произошел самый шизофренический инсайт в моей жизни. В первый
первый раз Чапаева с Пустотой (рекомендую, очень сильно, хотя идее
столько же, сколько цивилизации). Так вот, прочитал главу, где Чапаев
мучает Петра вопросом "А кто есть ты?". Что-то мне в этой главе запало
в душу и той же ночью приснился сон. Как изредка бывает, и как бывает
только во сне~--- с кристально чистой мыслью, которую никаким
фейсбуком не передашь, потому что это какой-то глубоко личное
переживание, на уровне базового понимания мироустройства.

Так вот, снится мне, что сидим мы с Чапаевым (Петькой?) и я, Чапаев
(Петька?) спорю с собеседником (а в контексте книги и, очевидно, нашей
реальности~--- с самим собой) о том, что такое свобода. Собеседник
у меня немного глупый, но понятливый. В смысле, наставник у меня
немного настойчивый, но очень крутой. Не буду вдаваться в подробности
диалога, тем более что я его детали забыл и весь кристалл здесь
изобразить не смогу. Скажу кратко, что мы прошлись от понимания
свободы, как "свободы от стен", проскочили мимо "свободы финансовой и
перемещений", чуть задержались на "свободе мысли" и в итоге пришли к
свободе от собственного воображения и свободе к ничто, к свободе от
пустоты и даже самого Ничто, свободе от собственного Я.  Это озарение
не слабо заиграло с не самым простым периодом в моей жизни, может быть
поэтому и зацепило.

Сон был предельно яркий, и не меньше поразило то, что я прочитал двумя
днями позже:

\nbsp{}— Эй, Василий Иванович!~--- тихо позвал я.

~--- Чего?~--- отозвался Чапаев.

~--- Я одну вещь понял,~--- сказал я.~--- Свобода бывает
только одна~--- когда ты свободен от всего, что строит ум. Эта
свобода называется "не знаю". Вы совершенно правы. Знаете, есть такое
выражение: "Мысль изреченная есть ложь". Чапаев, я вам скажу, что
мысль неизреченная - тоже ложь, потому что в любой мысли уже
присутствует изреченность.

~--- Это ты, Петька, хорошо изрек,~--- отозвался Чапаев.

~--- Как только я знаю,~--- продолжал я,~--- я уже не
свободен. Но я абсолютно свободен, когда не знаю. Свобода~--- это
самая большая тайна из всех. Они,~--- я ткнул пальцем в низкий
земляной потолок,~--- просто не знают, до какой степени они
свободны от всего. Они не знают, кто они на самом деле. Они... - меня
скрутило в спазмах неудержимого хохота, - они думают, что они ткачи…
